server:
  port: 8080

spring:
  application:
    name: catalog-service
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/catalog_db?authSource=admin
  mvc:
    problemdetails:
      enabled: true